/* Automatically generated by p4c-ebpf from router/top.p4 on Thu Sep 14 21:19:17 2023
 */
#include "ebpf_kernel.h"

#include <stdbool.h>
#include <string.h>
#include <linux/if_ether.h>
#include "psa.h"

#define EBPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
#define BYTES(w) ((w) / 8)
#define write_partial(a, w, s, v) do { *((u8*)a) = ((*((u8*)a)) & ~(EBPF_MASK(u8, w) << s)) | (v << s) ; } while (0)
#define write_byte(base, offset, v) do { *(u8*)((base) + (offset)) = (v); } while (0)
#define bpf_trace_message(fmt, ...)


#define CLONE_MAX_PORTS 64
#define CLONE_MAX_INSTANCES 1
#define CLONE_MAX_CLONES (CLONE_MAX_PORTS * CLONE_MAX_INSTANCES)
#define CLONE_MAX_SESSIONS 1024

#ifndef PSA_PORT_RECIRCULATE
#define PSA_PORT_RECIRCULATE 0
#endif
#define P4C_PSA_PORT_RECIRCULATE 0xfffffffa

struct internal_metadata {
    __u16 pkt_ether_type;
} __attribute__((aligned(4)));

struct list_key_t {
    __u32 port;
    __u16 instance;
};
typedef struct list_key_t elem_t;

struct element {
    struct clone_session_entry entry;
    elem_t next_id;
} __attribute__((aligned(4)));


struct metadata_t {
    u8 viaIP6[16]; /* bit<128> */
    u32 viaIP4; /* bit<32> */
    u32 vrf; /* bit<32> */
    u8 process; /* bit<8> */
};
struct empty_t {
};
struct ethernet_t {
    u64 dst; /* bit<48> */
    u64 src; /* bit<48> */
    u16 etherType; /* bit<16> */
    u8 ebpf_valid;
};
struct ip4_t {
    u8 version; /* bit<4> */
    u8 ihl; /* bit<4> */
    u8 dscp; /* bit<6> */
    u8 ecn; /* bit<2> */
    u16 len; /* bit<16> */
    u16 id; /* bit<16> */
    u8 flags; /* bit<3> */
    u16 fragOffset; /* bit<13> */
    u8 ttl; /* bit<8> */
    u8 protocol; /* bit<8> */
    u16 checksum; /* bit<16> */
    u32 srcAddr; /* bit<32> */
    u32 dstAddr; /* bit<32> */
    u8 ebpf_valid;
};
struct ip6_t {
    u8 version; /* bit<4> */
    u8 trafficClass; /* bit<8> */
    u32 flowLabel; /* bit<20> */
    u16 len; /* bit<16> */
    u8 nextHdr; /* bit<8> */
    u8 hopLimit; /* bit<8> */
    u8 srcAddr[16]; /* bit<128> */
    u8 dstAddr[16]; /* bit<128> */
    u8 ebpf_valid;
};
struct headers {
    struct ethernet_t ethernet; /* ethernet_t */
    struct ip4_t ip4; /* ip4_t */
    struct ip6_t ip6; /* ip6_t */
};
struct ingress_arp_resolve_ip4_key {
    u32 field0; /* meta.viaIP4 */
} __attribute__((aligned(4)));
#define INGRESS_ARP_RESOLVE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL 1
#define INGRESS_ARP_RESOLVE_IP4_ACT_INGRESS_SET_DST_MAC 2
struct ingress_arp_resolve_ip4_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
        } ingress_normal_path_to_kernel;
        struct {
            u64 dst_mac;
        } ingress_set_dst_mac;
    } u;
};
struct ingress_arp_resolve_ip6_key {
    u8 field0[16]; /* meta.viaIP6 */
} __attribute__((aligned(4)));
#define INGRESS_ARP_RESOLVE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL 1
#define INGRESS_ARP_RESOLVE_IP6_ACT_INGRESS_SET_DST_MAC 2
struct ingress_arp_resolve_ip6_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
        } ingress_normal_path_to_kernel;
        struct {
            u64 dst_mac;
        } ingress_set_dst_mac;
    } u;
};
struct ingress_forward_local_table_ip4_key {
    u32 field0; /* hdr.ip4.dstAddr */
} __attribute__((aligned(4)));
#define INGRESS_FORWARD_LOCAL_TABLE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL 1
#define INGRESS_FORWARD_LOCAL_TABLE_IP4_ACT_INGRESS_NO_ACTION 2
struct ingress_forward_local_table_ip4_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
        } ingress_normal_path_to_kernel;
        struct {
        } ingress_no_action;
    } u;
};
struct ingress_forward_local_table_ip6_key {
    u8 field0[16]; /* hdr.ip6.dstAddr */
} __attribute__((aligned(4)));
#define INGRESS_FORWARD_LOCAL_TABLE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL 1
#define INGRESS_FORWARD_LOCAL_TABLE_IP6_ACT_INGRESS_NO_ACTION 2
struct ingress_forward_local_table_ip6_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
        } ingress_normal_path_to_kernel;
        struct {
        } ingress_no_action;
    } u;
};
struct ingress_routing_table_ip4_key {
    u32 prefixlen;
    u32 field0; /* meta.vrf */
    u32 field1; /* hdr.ip4.dstAddr */
} __attribute__((aligned(4)));
#define INGRESS_ROUTING_TABLE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL 1
#define INGRESS_ROUTING_TABLE_IP4_ACT_INGRESS_FORWARD_IP4 2
struct ingress_routing_table_ip4_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
        } ingress_normal_path_to_kernel;
        struct {
            u32 port;
            u32 via;
        } ingress_forward_ip4;
    } u;
};
struct ingress_routing_table_ip6_key {
    u32 prefixlen;
    u32 field0; /* meta.vrf */
    u8 field1[16]; /* hdr.ip6.dstAddr */
} __attribute__((aligned(4)));
#define INGRESS_ROUTING_TABLE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL 1
#define INGRESS_ROUTING_TABLE_IP6_ACT_INGRESS_FORWARD_IP6 2
struct ingress_routing_table_ip6_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
        } ingress_normal_path_to_kernel;
        struct {
            u32 port;
            u8 via[16];
        } ingress_forward_ip6;
    } u;
};
struct ingress_src_mac_resolve_key {
    u32 field0; /* ostd.egress_port */
} __attribute__((aligned(4)));
#define INGRESS_SRC_MAC_RESOLVE_ACT_INGRESS_NORMAL_PATH_TO_KERNEL 1
#define INGRESS_SRC_MAC_RESOLVE_ACT_INGRESS_SET_SRC_MAC 2
struct ingress_src_mac_resolve_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
        } ingress_normal_path_to_kernel;
        struct {
            u64 src_mac;
        } ingress_set_src_mac;
    } u;
};
struct ingress_vrf_table_key {
    u32 field0; /* istd.ingress_port */
} __attribute__((aligned(4)));
#define INGRESS_VRF_TABLE_ACT_INGRESS_SET_VRF 1
#define INGRESS_VRF_TABLE_ACT_INGRESS_SET_DEFAULT_VRF 2
struct ingress_vrf_table_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
            u32 vrf;
        } ingress_set_vrf;
        struct {
        } ingress_set_default_vrf;
    } u;
};

struct lookup_tbl_val {
    u32 table[2048];
};

struct hdr_md {
    struct headers cpumap_hdr;
    struct metadata_t cpumap_usermeta;
    __u8 __hook;
};

REGISTER_START()
REGISTER_TABLE_INNER(clone_session_tbl_inner, BPF_MAP_TYPE_HASH, elem_t, struct element, 64, 1, 1)
BPF_ANNOTATE_KV_PAIR(clone_session_tbl_inner, elem_t, struct element)
REGISTER_TABLE_OUTER(clone_session_tbl, BPF_MAP_TYPE_ARRAY_OF_MAPS, __u32, __u32, 1024, 1, clone_session_tbl_inner)
BPF_ANNOTATE_KV_PAIR(clone_session_tbl, __u32, __u32)
REGISTER_TABLE_INNER(multicast_grp_tbl_inner, BPF_MAP_TYPE_HASH, elem_t, struct element, 64, 2, 2)
BPF_ANNOTATE_KV_PAIR(multicast_grp_tbl_inner, elem_t, struct element)
REGISTER_TABLE_OUTER(multicast_grp_tbl, BPF_MAP_TYPE_ARRAY_OF_MAPS, __u32, __u32, 1024, 2, multicast_grp_tbl_inner)
BPF_ANNOTATE_KV_PAIR(multicast_grp_tbl, __u32, __u32)
REGISTER_TABLE(ingress_arp_resolve_ip4, BPF_MAP_TYPE_HASH, struct ingress_arp_resolve_ip4_key, struct ingress_arp_resolve_ip4_value, 1024)
BPF_ANNOTATE_KV_PAIR(ingress_arp_resolve_ip4, struct ingress_arp_resolve_ip4_key, struct ingress_arp_resolve_ip4_value)
REGISTER_TABLE(ingress_arp_resolve_ip4_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_arp_resolve_ip4_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_arp_resolve_ip4_defaultAction, u32, struct ingress_arp_resolve_ip4_value)
REGISTER_TABLE(ingress_arp_resolve_ip6, BPF_MAP_TYPE_HASH, struct ingress_arp_resolve_ip6_key, struct ingress_arp_resolve_ip6_value, 1024)
BPF_ANNOTATE_KV_PAIR(ingress_arp_resolve_ip6, struct ingress_arp_resolve_ip6_key, struct ingress_arp_resolve_ip6_value)
REGISTER_TABLE(ingress_arp_resolve_ip6_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_arp_resolve_ip6_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_arp_resolve_ip6_defaultAction, u32, struct ingress_arp_resolve_ip6_value)
REGISTER_TABLE(ingress_forward_local_table_ip4, BPF_MAP_TYPE_HASH, struct ingress_forward_local_table_ip4_key, struct ingress_forward_local_table_ip4_value, 1024)
BPF_ANNOTATE_KV_PAIR(ingress_forward_local_table_ip4, struct ingress_forward_local_table_ip4_key, struct ingress_forward_local_table_ip4_value)
REGISTER_TABLE(ingress_forward_local_table_ip4_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_forward_local_table_ip4_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_forward_local_table_ip4_defaultAction, u32, struct ingress_forward_local_table_ip4_value)
REGISTER_TABLE(ingress_forward_local_table_ip6, BPF_MAP_TYPE_HASH, struct ingress_forward_local_table_ip6_key, struct ingress_forward_local_table_ip6_value, 1024)
BPF_ANNOTATE_KV_PAIR(ingress_forward_local_table_ip6, struct ingress_forward_local_table_ip6_key, struct ingress_forward_local_table_ip6_value)
REGISTER_TABLE(ingress_forward_local_table_ip6_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_forward_local_table_ip6_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_forward_local_table_ip6_defaultAction, u32, struct ingress_forward_local_table_ip6_value)
REGISTER_TABLE_FLAGS(ingress_routing_table_ip4, BPF_MAP_TYPE_LPM_TRIE, struct ingress_routing_table_ip4_key, struct ingress_routing_table_ip4_value, 1024, BPF_F_NO_PREALLOC)
BPF_ANNOTATE_KV_PAIR(ingress_routing_table_ip4, struct ingress_routing_table_ip4_key, struct ingress_routing_table_ip4_value)
REGISTER_TABLE(ingress_routing_table_ip4_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_routing_table_ip4_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_routing_table_ip4_defaultAction, u32, struct ingress_routing_table_ip4_value)
REGISTER_TABLE_FLAGS(ingress_routing_table_ip6, BPF_MAP_TYPE_LPM_TRIE, struct ingress_routing_table_ip6_key, struct ingress_routing_table_ip6_value, 1024, BPF_F_NO_PREALLOC)
BPF_ANNOTATE_KV_PAIR(ingress_routing_table_ip6, struct ingress_routing_table_ip6_key, struct ingress_routing_table_ip6_value)
REGISTER_TABLE(ingress_routing_table_ip6_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_routing_table_ip6_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_routing_table_ip6_defaultAction, u32, struct ingress_routing_table_ip6_value)
REGISTER_TABLE(ingress_src_mac_resolve, BPF_MAP_TYPE_HASH, struct ingress_src_mac_resolve_key, struct ingress_src_mac_resolve_value, 1024)
BPF_ANNOTATE_KV_PAIR(ingress_src_mac_resolve, struct ingress_src_mac_resolve_key, struct ingress_src_mac_resolve_value)
REGISTER_TABLE(ingress_src_mac_resolve_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_src_mac_resolve_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_src_mac_resolve_defaultAction, u32, struct ingress_src_mac_resolve_value)
REGISTER_TABLE(ingress_vrf_table, BPF_MAP_TYPE_HASH, struct ingress_vrf_table_key, struct ingress_vrf_table_value, 1024)
BPF_ANNOTATE_KV_PAIR(ingress_vrf_table, struct ingress_vrf_table_key, struct ingress_vrf_table_value)
REGISTER_TABLE(ingress_vrf_table_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_vrf_table_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_vrf_table_defaultAction, u32, struct ingress_vrf_table_value)
REGISTER_TABLE(hdr_md_cpumap, BPF_MAP_TYPE_PERCPU_ARRAY, u32, struct hdr_md, 2)
BPF_ANNOTATE_KV_PAIR(hdr_md_cpumap, u32, struct hdr_md)
REGISTER_TABLE(crc_lookup_tbl, BPF_MAP_TYPE_ARRAY, u32, struct lookup_tbl_val, 1)
BPF_ANNOTATE_KV_PAIR(crc_lookup_tbl, u32, struct lookup_tbl_val)
REGISTER_END()

static __always_inline
void crc16_update(u16 * reg, const u8 * data, u16 data_size, const u16 poly) {
    if (data_size <= 8)
        data += data_size - 1;
    #pragma clang loop unroll(full)
    for (u16 i = 0; i < data_size; i++) {
        bpf_trace_message("CRC16: data byte: %x\n", *data);
        *reg ^= *data;
        for (u8 bit = 0; bit < 8; bit++) {
            *reg = (*reg) & 1 ? ((*reg) >> 1) ^ poly : (*reg) >> 1;
        }
        if (data_size <= 8)
            data--;
        else
            data++;
    }
}
static __always_inline u16 crc16_finalize(u16 reg) {
    return reg;
}
static __always_inline
void crc32_update(u32 * reg, const u8 * data, u16 data_size, const u32 poly) {
    u32* current = (u32*) data;
    struct lookup_tbl_val* lookup_table;
    u32 index = 0;
    lookup_table = BPF_MAP_LOOKUP_ELEM(crc_lookup_tbl, &index);
    u32 lookup_key = 0;
    u32 lookup_value = 0;
    u32 lookup_value1 = 0;
    u32 lookup_value2 = 0;
    u32 lookup_value3 = 0;
    u32 lookup_value4 = 0;
    u32 lookup_value5 = 0;
    u32 lookup_value6 = 0;
    u32 lookup_value7 = 0;
    u32 lookup_value8 = 0;
    u16 tmp = 0;
    if (lookup_table != NULL) {
        for (u16 i = data_size; i >= 8; i -= 8) {
            /* Vars one and two will have swapped byte order if data_size == 8 */
            if (data_size == 8) current = data + 4;
            bpf_trace_message("CRC32: data dword: %x\n", *current);
            u32 one = (data_size == 8 ? __builtin_bswap32(*current--) : *current++) ^ *reg;
            bpf_trace_message("CRC32: data dword: %x\n", *current);
            u32 two = (data_size == 8 ? __builtin_bswap32(*current--) : *current++);
            lookup_key = (one & 0x000000FF);
            lookup_value8 = lookup_table->table[(u16)(1792 + (u8)lookup_key)];
            lookup_key = (one >> 8) & 0x000000FF;
            lookup_value7 = lookup_table->table[(u16)(1536 + (u8)lookup_key)];
            lookup_key = (one >> 16) & 0x000000FF;
            lookup_value6 = lookup_table->table[(u16)(1280 + (u8)lookup_key)];
            lookup_key = one >> 24;
            lookup_value5 = lookup_table->table[(u16)(1024 + (u8)(lookup_key))];
            lookup_key = (two & 0x000000FF);
            lookup_value4 = lookup_table->table[(u16)(768 + (u8)lookup_key)];
            lookup_key = (two >> 8) & 0x000000FF;
            lookup_value3 = lookup_table->table[(u16)(512 + (u8)lookup_key)];
            lookup_key = (two >> 16) & 0x000000FF;
            lookup_value2 = lookup_table->table[(u16)(256 + (u8)lookup_key)];
            lookup_key = two >> 24;
            lookup_value1 = lookup_table->table[(u8)(lookup_key)];
            *reg = lookup_value8 ^ lookup_value7 ^ lookup_value6 ^ lookup_value5 ^
                   lookup_value4 ^ lookup_value3 ^ lookup_value2 ^ lookup_value1;
            tmp += 8;
        }
        volatile int std_algo_lookup_key = 0;
        if (data_size < 8) {
            unsigned char *currentChar = (unsigned char *) current;
            currentChar += data_size - 1;
            for (u16 i = tmp; i < data_size; i++) {
                bpf_trace_message("CRC32: data byte: %x\n", *currentChar);
                std_algo_lookup_key = (u32)(((*reg) & 0xFF) ^ *currentChar--);
                if (std_algo_lookup_key >= 0) {
                    lookup_value = lookup_table->table[(u8)(std_algo_lookup_key & 255)];
                }
                *reg = ((*reg) >> 8) ^ lookup_value;
            }
        } else {
            /* Consume data not processed by slice-by-8 algorithm above, these data are in network byte order */
            unsigned char *currentChar = (unsigned char *) current;
            for (u16 i = tmp; i < data_size; i++) {
                bpf_trace_message("CRC32: data byte: %x\n", *currentChar);
                std_algo_lookup_key = (u32)(((*reg) & 0xFF) ^ *currentChar++);
                if (std_algo_lookup_key >= 0) {
                    lookup_value = lookup_table->table[(u8)(std_algo_lookup_key & 255)];
                }
                *reg = ((*reg) >> 8) ^ lookup_value;
            }
        }
    }
}
static __always_inline u32 crc32_finalize(u32 reg) {
    return reg ^ 0xFFFFFFFF;
}
inline u16 csum16_add(u16 csum, u16 addend) {
    u16 res = csum;
    res += addend;
    return (res + (res < addend));
}
inline u16 csum16_sub(u16 csum, u16 addend) {
    return csum16_add(csum, ~addend);
}
static __always_inline
int do_for_each(SK_BUFF *skb, void *map, unsigned int max_iter, void (*a)(SK_BUFF *, void *))
{
    elem_t head_idx = {0, 0};
    struct element *elem = bpf_map_lookup_elem(map, &head_idx);
    if (!elem) {
        return -1;
    }
    if (elem->next_id.port == 0 && elem->next_id.instance == 0) {
               return 0;
    }
    elem_t next_id = elem->next_id;
    for (unsigned int i = 0; i < max_iter; i++) {
        struct element *elem = bpf_map_lookup_elem(map, &next_id);
        if (!elem) {
            break;
        }
        a(skb, &elem->entry);
        if (elem->next_id.port == 0 && elem->next_id.instance == 0) {
            break;
        }
        next_id = elem->next_id;
    }
    return 0;
}

static __always_inline
void do_clone(SK_BUFF *skb, void *data)
{
    struct clone_session_entry *entry = (struct clone_session_entry *) data;
    bpf_clone_redirect(skb, entry->egress_port, 0);
}

static __always_inline
int do_packet_clones(SK_BUFF * skb, void * map, __u32 session_id, PSA_PacketPath_t new_pkt_path, __u8 caller_id)
{
    struct psa_global_metadata * meta = (struct psa_global_metadata *) skb->cb;
    void * inner_map;
    inner_map = bpf_map_lookup_elem(map, &session_id);
    if (inner_map != NULL) {
        PSA_PacketPath_t original_pkt_path = meta->packet_path;
        meta->packet_path = new_pkt_path;
        if (do_for_each(skb, inner_map, CLONE_MAX_CLONES, &do_clone) < 0) {
            return -1;
        }
        meta->packet_path = original_pkt_path;
    } else {
    }
    return 0;
 }

static __always_inline
void add_prefix_and_entries(__u32 nr_entries,
            __u32 tuple_id,
            void *tuples_map,
            void *prefixes_map,
            void *key_mask,
            void *value_mask,
            void *keysPtrs[],
            void *valuesPtrs[]) {
    int ret = bpf_map_update_elem(prefixes_map, key_mask, value_mask, BPF_ANY);
    if (ret) {
        return;
    }
    if (nr_entries == 0) {
        return;
    }
    struct bpf_elf_map *tuple = bpf_map_lookup_elem(tuples_map, &tuple_id);
    if (tuple) {
        for (__u32 i = 0; i < nr_entries; i++) {
            int ret = bpf_map_update_elem(tuple, keysPtrs[i], valuesPtrs[i], BPF_ANY);
            if (ret) {
                return;
            } else {
            }
        }
    } else {
        return;
    }
}

SEC("classifier/map-initializer")
int map_initializer() {
    u32 ebpf_zero = 0;
    struct ingress_arp_resolve_ip4_value value_0 = {
        .action = INGRESS_ARP_RESOLVE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL,
        .u = {.ingress_normal_path_to_kernel = {}}
    };
    int ret = BPF_MAP_UPDATE_ELEM(ingress_arp_resolve_ip4_defaultAction, &ebpf_zero, &value_0, BPF_ANY);
    struct ingress_arp_resolve_ip6_value value_1 = {
        .action = INGRESS_ARP_RESOLVE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL,
        .u = {.ingress_normal_path_to_kernel = {}}
    };
    int ret_0 = BPF_MAP_UPDATE_ELEM(ingress_arp_resolve_ip6_defaultAction, &ebpf_zero, &value_1, BPF_ANY);
    struct ingress_forward_local_table_ip4_value value_2 = {
        .action = INGRESS_FORWARD_LOCAL_TABLE_IP4_ACT_INGRESS_NO_ACTION,
        .u = {.ingress_no_action = {}}
    };
    int ret_1 = BPF_MAP_UPDATE_ELEM(ingress_forward_local_table_ip4_defaultAction, &ebpf_zero, &value_2, BPF_ANY);
    struct ingress_forward_local_table_ip6_value value_3 = {
        .action = INGRESS_FORWARD_LOCAL_TABLE_IP6_ACT_INGRESS_NO_ACTION,
        .u = {.ingress_no_action = {}}
    };
    int ret_2 = BPF_MAP_UPDATE_ELEM(ingress_forward_local_table_ip6_defaultAction, &ebpf_zero, &value_3, BPF_ANY);
    struct ingress_routing_table_ip4_value value_4 = {
        .action = INGRESS_ROUTING_TABLE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL,
        .u = {.ingress_normal_path_to_kernel = {}}
    };
    int ret_3 = BPF_MAP_UPDATE_ELEM(ingress_routing_table_ip4_defaultAction, &ebpf_zero, &value_4, BPF_ANY);
    struct ingress_routing_table_ip6_value value_5 = {
        .action = INGRESS_ROUTING_TABLE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL,
        .u = {.ingress_normal_path_to_kernel = {}}
    };
    int ret_4 = BPF_MAP_UPDATE_ELEM(ingress_routing_table_ip6_defaultAction, &ebpf_zero, &value_5, BPF_ANY);
    struct ingress_src_mac_resolve_value value_6 = {
        .action = INGRESS_SRC_MAC_RESOLVE_ACT_INGRESS_NORMAL_PATH_TO_KERNEL,
        .u = {.ingress_normal_path_to_kernel = {}}
    };
    int ret_5 = BPF_MAP_UPDATE_ELEM(ingress_src_mac_resolve_defaultAction, &ebpf_zero, &value_6, BPF_ANY);
    struct ingress_vrf_table_value value_7 = {
        .action = INGRESS_VRF_TABLE_ACT_INGRESS_SET_DEFAULT_VRF,
        .u = {.ingress_set_default_vrf = {}}
    };
    int ret_6 = BPF_MAP_UPDATE_ELEM(ingress_vrf_table_defaultAction, &ebpf_zero, &value_7, BPF_ANY);

    u32 lookup_tbl_key = 0;
    struct lookup_tbl_val* lookup_tbl_value = BPF_MAP_LOOKUP_ELEM(crc_lookup_tbl, &lookup_tbl_key);
    if (lookup_tbl_value != NULL){
        for (u16 i = 0; i <= 255; i++){
            u32 crc = i;
            for (u16 j = 0; j < 8; j++){
                crc = (crc >> 1) ^ ((crc & 1) * 3988292384);
            }
            lookup_tbl_value->table[i] = crc;
        }
        for (u16 i = 0; i <= 255; i++){
            lookup_tbl_value->table[256+i] = (lookup_tbl_value->table[0+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[0+i] & 0xFF)];
            lookup_tbl_value->table[512+i] = (lookup_tbl_value->table[256+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[256+i] & 0xFF)];
            lookup_tbl_value->table[768+i] = (lookup_tbl_value->table[512+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[512+i] & 0xFF)];
            lookup_tbl_value->table[1024+i] = (lookup_tbl_value->table[768+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[768+i] & 0xFF)];
            lookup_tbl_value->table[1280+i] = (lookup_tbl_value->table[1024+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[1024+i] & 0xFF)];
            lookup_tbl_value->table[1536+i] = (lookup_tbl_value->table[1280+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[1280+i] & 0xFF)];
            lookup_tbl_value->table[1792+i] = (lookup_tbl_value->table[1536+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[1536+i] & 0xFF)];
        }
    }
    return 0;
}

SEC("xdp/xdp-ingress")
int xdp_func(struct xdp_md *skb) {
        void *data_end = (void *)(long)skb->data_end;
    struct ethhdr *eth = (struct ethhdr *)(long)skb->data;
    if ((void *)((struct ethhdr *) eth + 1) > data_end) {
        return XDP_ABORTED;
    }
    if (eth->h_proto == bpf_htons(0x0800) || eth->h_proto == bpf_htons(0x86DD)) {
        return XDP_PASS;
    }

    struct internal_metadata *meta;
    int ret = bpf_xdp_adjust_meta(skb, -(int)sizeof(*meta));
    if (ret < 0) {
        return XDP_ABORTED;
    }
    meta = (struct internal_metadata *)(unsigned long)skb->data_meta;
    eth = (void *)(long)skb->data;
    data_end = (void *)(long)skb->data_end;
    if ((void *) ((struct internal_metadata *) meta + 1) > (void *)(long)skb->data)
        return XDP_ABORTED;
    if ((void *)((struct ethhdr *) eth + 1) > data_end) {
        return XDP_ABORTED;
    }
    if (meta->pkt_ether_type != 0)
        return XDP_PASS;
    meta->pkt_ether_type = eth->h_proto;
    eth->h_proto = bpf_htons(0x0800);

    return XDP_PASS;
}
static __always_inline int process(struct __sk_buff *skb, struct headers *parsed_hdr, struct psa_ingress_output_metadata_t *ostd, struct psa_global_metadata *compiler_meta__, struct empty_t *resubmit_meta)
{
    unsigned ebpf_packetOffsetInBits = 0;
    unsigned ebpf_packetOffsetInBits_save = 0;
    ParserError_t ebpf_errorCode = NoError;
    void* pkt = ((void*)(long)skb->data);
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u32 ebpf_zero = 0;
    u32 ebpf_one = 1;
    unsigned char ebpf_byte;
    u32 pkt_len = skb->len;
    u32 ebpf_input_port = skb->ifindex;
    if (ebpf_input_port == PSA_PORT_RECIRCULATE) {
        ebpf_input_port = P4C_PSA_PORT_RECIRCULATE;
    }

    struct metadata_t *meta;
    struct hdr_md *hdrMd;

    hdrMd = BPF_MAP_LOOKUP_ELEM(hdr_md_cpumap, &ebpf_zero);
    if (!hdrMd)
        return TC_ACT_SHOT;
    __builtin_memset(hdrMd, 0, sizeof(struct hdr_md));

    parsed_hdr = &(hdrMd->cpumap_hdr);
    meta = &(hdrMd->cpumap_usermeta);
    {
        struct psa_ingress_parser_input_metadata_t istd = {
            .ingress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
        };
        goto start;
        parse_ip4: {
/* extract(parsed_hdr->ip4) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->ip4.version = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 4) & EBPF_MASK(u8, 4));
            ebpf_packetOffsetInBits += 4;

            parsed_hdr->ip4.ihl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u8, 4));
            ebpf_packetOffsetInBits += 4;

            parsed_hdr->ip4.dscp = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 2) & EBPF_MASK(u8, 6));
            ebpf_packetOffsetInBits += 6;

            parsed_hdr->ip4.ecn = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u8, 2));
            ebpf_packetOffsetInBits += 2;

            parsed_hdr->ip4.len = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ip4.id = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ip4.flags = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 5) & EBPF_MASK(u8, 3));
            ebpf_packetOffsetInBits += 3;

            parsed_hdr->ip4.fragOffset = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u16, 13));
            ebpf_packetOffsetInBits += 13;

            parsed_hdr->ip4.ttl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ip4.protocol = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ip4.checksum = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ip4.srcAddr = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ip4.dstAddr = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ip4.ebpf_valid = 1;

;
             goto accept;
        }
        parse_ip6: {
/* extract(parsed_hdr->ip6) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 320 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->ip6.version = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 4) & EBPF_MASK(u8, 4));
            ebpf_packetOffsetInBits += 4;

            parsed_hdr->ip6.trafficClass = (u8)((load_half(pkt, BYTES(ebpf_packetOffsetInBits)) >> 4) & EBPF_MASK(u8, 8));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ip6.flowLabel = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits)) >> 8) & EBPF_MASK(u32, 20));
            ebpf_packetOffsetInBits += 20;

            parsed_hdr->ip6.len = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ip6.nextHdr = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ip6.hopLimit = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ip6.srcAddr[0] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0) >> 0));
            parsed_hdr->ip6.srcAddr[1] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1) >> 0));
            parsed_hdr->ip6.srcAddr[2] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2) >> 0));
            parsed_hdr->ip6.srcAddr[3] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3) >> 0));
            parsed_hdr->ip6.srcAddr[4] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4) >> 0));
            parsed_hdr->ip6.srcAddr[5] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5) >> 0));
            parsed_hdr->ip6.srcAddr[6] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 6) >> 0));
            parsed_hdr->ip6.srcAddr[7] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 7) >> 0));
            parsed_hdr->ip6.srcAddr[8] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 8) >> 0));
            parsed_hdr->ip6.srcAddr[9] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 9) >> 0));
            parsed_hdr->ip6.srcAddr[10] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 10) >> 0));
            parsed_hdr->ip6.srcAddr[11] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 11) >> 0));
            parsed_hdr->ip6.srcAddr[12] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 12) >> 0));
            parsed_hdr->ip6.srcAddr[13] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 13) >> 0));
            parsed_hdr->ip6.srcAddr[14] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 14) >> 0));
            parsed_hdr->ip6.srcAddr[15] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 15) >> 0));
            ebpf_packetOffsetInBits += 128;

            parsed_hdr->ip6.dstAddr[0] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0) >> 0));
            parsed_hdr->ip6.dstAddr[1] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1) >> 0));
            parsed_hdr->ip6.dstAddr[2] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2) >> 0));
            parsed_hdr->ip6.dstAddr[3] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3) >> 0));
            parsed_hdr->ip6.dstAddr[4] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4) >> 0));
            parsed_hdr->ip6.dstAddr[5] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5) >> 0));
            parsed_hdr->ip6.dstAddr[6] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 6) >> 0));
            parsed_hdr->ip6.dstAddr[7] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 7) >> 0));
            parsed_hdr->ip6.dstAddr[8] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 8) >> 0));
            parsed_hdr->ip6.dstAddr[9] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 9) >> 0));
            parsed_hdr->ip6.dstAddr[10] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 10) >> 0));
            parsed_hdr->ip6.dstAddr[11] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 11) >> 0));
            parsed_hdr->ip6.dstAddr[12] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 12) >> 0));
            parsed_hdr->ip6.dstAddr[13] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 13) >> 0));
            parsed_hdr->ip6.dstAddr[14] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 14) >> 0));
            parsed_hdr->ip6.dstAddr[15] = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 15) >> 0));
            ebpf_packetOffsetInBits += 128;

            parsed_hdr->ip6.ebpf_valid = 1;

;
             goto accept;
        }
        start: {
/* extract(parsed_hdr->ethernet) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->ethernet.dst = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.src = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.etherType = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ethernet.ebpf_valid = 1;

;
            u16 select_0;
            select_0 = parsed_hdr->ethernet.etherType;
            if (select_0 == 0x800)goto parse_ip4;
            if (select_0 == 0x86dd)goto parse_ip6;
            if ((select_0 & 0x0) == (0x0 & 0x0))goto accept;
            else goto reject;
        }

        reject: {
            if (ebpf_errorCode == 0) {
                return TC_ACT_SHOT;
            }
            goto accept;
        }

    }

    accept: {
        struct psa_ingress_input_metadata_t istd = {
            .ingress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
            .parser_error = ebpf_errorCode,
    };
        u8 hit;
        {
if (!/* parsed_hdr->ip4.isValid() */
            parsed_hdr->ip4.ebpf_valid && !/* parsed_hdr->ip6.isValid() */
            parsed_hdr->ip6.ebpf_valid) {
/* normal_path_to_kernel_7() */
{
                    ostd->drop = false;
                                        ostd->egress_port = 0;
                                        meta->process = 0;
                };            }

            else {
/* setup_action() */
{
                    meta->process = 1;
                                        ostd->clone = false;
                };
                /* vrf_table_0.apply() */
                {
                    /* construct key */
                    struct ingress_vrf_table_key key = {};
                    key.field0 = istd.ingress_port;
                    /* value */
                    struct ingress_vrf_table_value *value = NULL;
                    /* perform lookup */
                    value = BPF_MAP_LOOKUP_ELEM(ingress_vrf_table, &key);
                    if (value == NULL) {
                        /* miss; find default action */
                        hit = 0;
                        value = BPF_MAP_LOOKUP_ELEM(ingress_vrf_table_defaultAction, &ebpf_zero);
                    } else {
                        hit = 1;
                    }
                    if (value != NULL) {
                        /* run action */
                        switch (value->action) {
                            case INGRESS_VRF_TABLE_ACT_INGRESS_SET_VRF: 
                                {
                                    meta->vrf = value->u.ingress_set_vrf.vrf;
                                }
                                break;
                            case INGRESS_VRF_TABLE_ACT_INGRESS_SET_DEFAULT_VRF: 
                                {
                                    meta->vrf = 254;
                                }
                                break;
                            default:
                                return TC_ACT_SHOT;
                        }
                    } else {
                        return TC_ACT_SHOT;
;
                    }
                }
;
                if (/* parsed_hdr->ip4.isValid() */
                parsed_hdr->ip4.ebpf_valid) {
/* forward_local_table_ip4_0.apply() */
                    {
                        /* construct key */
                        struct ingress_forward_local_table_ip4_key key = {};
                        key.field0 = parsed_hdr->ip4.dstAddr;
                        /* value */
                        struct ingress_forward_local_table_ip4_value *value = NULL;
                        /* perform lookup */
                        value = BPF_MAP_LOOKUP_ELEM(ingress_forward_local_table_ip4, &key);
                        if (value == NULL) {
                            /* miss; find default action */
                            hit = 0;
                            value = BPF_MAP_LOOKUP_ELEM(ingress_forward_local_table_ip4_defaultAction, &ebpf_zero);
                        } else {
                            hit = 1;
                        }
                        if (value != NULL) {
                            /* run action */
                            switch (value->action) {
                                case INGRESS_FORWARD_LOCAL_TABLE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                    {
                                        ostd->drop = false;
                                                                                ostd->egress_port = 0;
                                                                                meta->process = 0;
                                    }
                                    break;
                                case INGRESS_FORWARD_LOCAL_TABLE_IP4_ACT_INGRESS_NO_ACTION: 
                                    {
                                    }
                                    break;
                                default:
                                    return TC_ACT_SHOT;
                            }
                        } else {
                            return TC_ACT_SHOT;
;
                        }
                    }
;
                    if (meta->process == 1) {
/* routing_table_ip4_0.apply() */
                        {
                            /* construct key */
                            struct ingress_routing_table_ip4_key key = {};
                            key.prefixlen = sizeof(key)*8 - 32;
                            key.field0 = meta->vrf;
                            key.field1 = bpf_htonl(parsed_hdr->ip4.dstAddr);
                            /* value */
                            struct ingress_routing_table_ip4_value *value = NULL;
                            /* perform lookup */
                            value = BPF_MAP_LOOKUP_ELEM(ingress_routing_table_ip4, &key);
                            if (value == NULL) {
                                /* miss; find default action */
                                hit = 0;
                                value = BPF_MAP_LOOKUP_ELEM(ingress_routing_table_ip4_defaultAction, &ebpf_zero);
                            } else {
                                hit = 1;
                            }
                            if (value != NULL) {
                                /* run action */
                                switch (value->action) {
                                    case INGRESS_ROUTING_TABLE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                        {
                                            ostd->drop = false;
                                                                                        ostd->egress_port = 0;
                                                                                        meta->process = 0;
                                        }
                                        break;
                                    case INGRESS_ROUTING_TABLE_IP4_ACT_INGRESS_FORWARD_IP4: 
                                        {
if (value->u.ingress_forward_ip4.via != 0) {
                                                meta->viaIP4 = value->u.ingress_forward_ip4.via;                                            }

                                            else {
                                                meta->viaIP4 = parsed_hdr->ip4.dstAddr;                                            }

                                                                                        ostd->drop = false;
                                                                                        ostd->egress_port = value->u.ingress_forward_ip4.port;
                                        }
                                        break;
                                    default:
                                        return TC_ACT_SHOT;
                                }
                            } else {
                                return TC_ACT_SHOT;
;
                            }
                        }
;                    }

                    if (meta->process == 1) {
/* arp_resolve_ip4_0.apply() */
                        {
                            /* construct key */
                            struct ingress_arp_resolve_ip4_key key = {};
                            key.field0 = meta->viaIP4;
                            /* value */
                            struct ingress_arp_resolve_ip4_value *value = NULL;
                            /* perform lookup */
                            value = BPF_MAP_LOOKUP_ELEM(ingress_arp_resolve_ip4, &key);
                            if (value == NULL) {
                                /* miss; find default action */
                                hit = 0;
                                value = BPF_MAP_LOOKUP_ELEM(ingress_arp_resolve_ip4_defaultAction, &ebpf_zero);
                            } else {
                                hit = 1;
                            }
                            if (value != NULL) {
                                /* run action */
                                switch (value->action) {
                                    case INGRESS_ARP_RESOLVE_IP4_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                        {
                                            ostd->drop = false;
                                                                                        ostd->egress_port = 0;
                                                                                        meta->process = 0;
                                        }
                                        break;
                                    case INGRESS_ARP_RESOLVE_IP4_ACT_INGRESS_SET_DST_MAC: 
                                        {
                                            parsed_hdr->ethernet.dst = value->u.ingress_set_dst_mac.dst_mac;
                                        }
                                        break;
                                    default:
                                        return TC_ACT_SHOT;
                                }
                            } else {
                                return TC_ACT_SHOT;
;
                            }
                        }
;                    }

                    if (meta->process == 1) {
/* src_mac_resolve_0.apply() */
                        {
                            /* construct key */
                            struct ingress_src_mac_resolve_key key = {};
                            key.field0 = ostd->egress_port;
                            /* value */
                            struct ingress_src_mac_resolve_value *value = NULL;
                            /* perform lookup */
                            value = BPF_MAP_LOOKUP_ELEM(ingress_src_mac_resolve, &key);
                            if (value == NULL) {
                                /* miss; find default action */
                                hit = 0;
                                value = BPF_MAP_LOOKUP_ELEM(ingress_src_mac_resolve_defaultAction, &ebpf_zero);
                            } else {
                                hit = 1;
                            }
                            if (value != NULL) {
                                /* run action */
                                switch (value->action) {
                                    case INGRESS_SRC_MAC_RESOLVE_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                        {
                                            ostd->drop = false;
                                                                                        ostd->egress_port = 0;
                                                                                        meta->process = 0;
                                        }
                                        break;
                                    case INGRESS_SRC_MAC_RESOLVE_ACT_INGRESS_SET_SRC_MAC: 
                                        {
                                            parsed_hdr->ethernet.src = value->u.ingress_set_src_mac.src_mac;
                                        }
                                        break;
                                    default:
                                        return TC_ACT_SHOT;
                                }
                            } else {
                                return TC_ACT_SHOT;
;
                            }
                        }
;                    }

                }
                if (/* parsed_hdr->ip6.isValid() */
                parsed_hdr->ip6.ebpf_valid) {
/* forward_local_table_ip6_0.apply() */
                    {
                        /* construct key */
                        struct ingress_forward_local_table_ip6_key key = {};
                        __builtin_memcpy(&(key.field0[0]), &(parsed_hdr->ip6.dstAddr[0]), 16);
                        /* value */
                        struct ingress_forward_local_table_ip6_value *value = NULL;
                        /* perform lookup */
                        value = BPF_MAP_LOOKUP_ELEM(ingress_forward_local_table_ip6, &key);
                        if (value == NULL) {
                            /* miss; find default action */
                            hit = 0;
                            value = BPF_MAP_LOOKUP_ELEM(ingress_forward_local_table_ip6_defaultAction, &ebpf_zero);
                        } else {
                            hit = 1;
                        }
                        if (value != NULL) {
                            /* run action */
                            switch (value->action) {
                                case INGRESS_FORWARD_LOCAL_TABLE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                    {
                                        ostd->drop = false;
                                                                                ostd->egress_port = 0;
                                                                                meta->process = 0;
                                    }
                                    break;
                                case INGRESS_FORWARD_LOCAL_TABLE_IP6_ACT_INGRESS_NO_ACTION: 
                                    {
                                    }
                                    break;
                                default:
                                    return TC_ACT_SHOT;
                            }
                        } else {
                            return TC_ACT_SHOT;
;
                        }
                    }
;
                    if (meta->process == 1) {
/* routing_table_ip6_0.apply() */
                        {
                            /* construct key */
                            struct ingress_routing_table_ip6_key key = {};
                            key.prefixlen = sizeof(key)*8 - 32;
                            key.field0 = meta->vrf;
                            __builtin_memcpy(&(key.field1[0]), &(parsed_hdr->ip6.dstAddr[0]), 16);
                            /* value */
                            struct ingress_routing_table_ip6_value *value = NULL;
                            /* perform lookup */
                            value = BPF_MAP_LOOKUP_ELEM(ingress_routing_table_ip6, &key);
                            if (value == NULL) {
                                /* miss; find default action */
                                hit = 0;
                                value = BPF_MAP_LOOKUP_ELEM(ingress_routing_table_ip6_defaultAction, &ebpf_zero);
                            } else {
                                hit = 1;
                            }
                            if (value != NULL) {
                                /* run action */
                                switch (value->action) {
                                    case INGRESS_ROUTING_TABLE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                        {
                                            ostd->drop = false;
                                                                                        ostd->egress_port = 0;
                                                                                        meta->process = 0;
                                        }
                                        break;
                                    case INGRESS_ROUTING_TABLE_IP6_ACT_INGRESS_FORWARD_IP6: 
                                        {
                                            __uint8_t tmp[16] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, };
if ((value->u.ingress_forward_ip6.via[0] == 0) &&
    (value->u.ingress_forward_ip6.via[1] == 0) &&
    (value->u.ingress_forward_ip6.via[2] == 0) &&
    (value->u.ingress_forward_ip6.via[3] == 0) &&
    (value->u.ingress_forward_ip6.via[4] == 0) &&
    (value->u.ingress_forward_ip6.via[5] == 0) &&
    (value->u.ingress_forward_ip6.via[6] == 0) &&
    (value->u.ingress_forward_ip6.via[7] == 0) &&
    (value->u.ingress_forward_ip6.via[8] == 0) &&
    (value->u.ingress_forward_ip6.via[9] == 0) &&
    (value->u.ingress_forward_ip6.via[10] == 0) &&
    (value->u.ingress_forward_ip6.via[11] == 0) &&
    (value->u.ingress_forward_ip6.via[12] == 0) &&
    (value->u.ingress_forward_ip6.via[13] == 0) &&
    (value->u.ingress_forward_ip6.via[14] == 0) &&
    (value->u.ingress_forward_ip6.via[15] == 0)) {
                                                __builtin_memcpy(&meta->viaIP6, &parsed_hdr->ip6.dstAddr, 16);                                            }

                                            else {
                                                __builtin_memcpy(&meta->viaIP6, &value->u.ingress_forward_ip6.via, 16);                                            }

                                                                                        ostd->drop = false;
                                                                                        ostd->egress_port = value->u.ingress_forward_ip6.port;
                                        }
                                        break;
                                    default:
                                        return TC_ACT_SHOT;
                                }
                            } else {
                                return TC_ACT_SHOT;
;
                            }
                        }
;                    }

                    if (meta->process == 1) {
/* arp_resolve_ip6_0.apply() */
                        {
                            /* construct key */
                            struct ingress_arp_resolve_ip6_key key = {};
                            __builtin_memcpy(&(key.field0[0]), &(meta->viaIP6[0]), 16);
                            /* value */
                            struct ingress_arp_resolve_ip6_value *value = NULL;
                            /* perform lookup */
                            value = BPF_MAP_LOOKUP_ELEM(ingress_arp_resolve_ip6, &key);
                            if (value == NULL) {
                                /* miss; find default action */
                                hit = 0;
                                value = BPF_MAP_LOOKUP_ELEM(ingress_arp_resolve_ip6_defaultAction, &ebpf_zero);
                            } else {
                                hit = 1;
                            }
                            if (value != NULL) {
                                /* run action */
                                switch (value->action) {
                                    case INGRESS_ARP_RESOLVE_IP6_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                        {
                                            ostd->drop = false;
                                                                                        ostd->egress_port = 0;
                                                                                        meta->process = 0;
                                        }
                                        break;
                                    case INGRESS_ARP_RESOLVE_IP6_ACT_INGRESS_SET_DST_MAC: 
                                        {
                                            parsed_hdr->ethernet.dst = value->u.ingress_set_dst_mac.dst_mac;
                                        }
                                        break;
                                    default:
                                        return TC_ACT_SHOT;
                                }
                            } else {
                                return TC_ACT_SHOT;
;
                            }
                        }
;                    }

                    if (meta->process == 1) {
/* src_mac_resolve_0.apply() */
                        {
                            /* construct key */
                            struct ingress_src_mac_resolve_key key = {};
                            key.field0 = ostd->egress_port;
                            /* value */
                            struct ingress_src_mac_resolve_value *value = NULL;
                            /* perform lookup */
                            value = BPF_MAP_LOOKUP_ELEM(ingress_src_mac_resolve, &key);
                            if (value == NULL) {
                                /* miss; find default action */
                                hit = 0;
                                value = BPF_MAP_LOOKUP_ELEM(ingress_src_mac_resolve_defaultAction, &ebpf_zero);
                            } else {
                                hit = 1;
                            }
                            if (value != NULL) {
                                /* run action */
                                switch (value->action) {
                                    case INGRESS_SRC_MAC_RESOLVE_ACT_INGRESS_NORMAL_PATH_TO_KERNEL: 
                                        {
                                            ostd->drop = false;
                                                                                        ostd->egress_port = 0;
                                                                                        meta->process = 0;
                                        }
                                        break;
                                    case INGRESS_SRC_MAC_RESOLVE_ACT_INGRESS_SET_SRC_MAC: 
                                        {
                                            parsed_hdr->ethernet.src = value->u.ingress_set_src_mac.src_mac;
                                        }
                                        break;
                                    default:
                                        return TC_ACT_SHOT;
                                }
                            } else {
                                return TC_ACT_SHOT;
;
                            }
                        }
;                    }

                }
            }
        }
    }
    {
{
;
            ;
            ;
        }

        
        if (ostd->clone) {
            do_packet_clones(skb, &clone_session_tbl, ostd->clone_session_id, CLONE_I2E, 1);
        }
        if (ostd->drop) {
            return TC_ACT_SHOT;
        }
        if (ostd->resubmit) {
            compiler_meta__->packet_path = RESUBMIT;
            return TC_ACT_UNSPEC;
        }
        int outHeaderLength = 0;
        if (parsed_hdr->ethernet.ebpf_valid) {
            outHeaderLength += 112;
        }
;        if (parsed_hdr->ip4.ebpf_valid) {
            outHeaderLength += 160;
        }
;        if (parsed_hdr->ip6.ebpf_valid) {
            outHeaderLength += 320;
        }
;
        int outHeaderOffset = BYTES(outHeaderLength) - BYTES(ebpf_packetOffsetInBits);
        if (outHeaderOffset != 0) {
            int returnCode = 0;
            returnCode = bpf_skb_adjust_room(skb, outHeaderOffset, 1, 0);
            if (returnCode) {
                return TC_ACT_SHOT;
            }
        }
        pkt = ((void*)(long)skb->data);
        ebpf_packetEnd = ((void*)(long)skb->data_end);
        ebpf_packetOffsetInBits = 0;
        if (parsed_hdr->ethernet.ebpf_valid) {
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112)) {
                return TC_ACT_SHOT;
            }
            
            parsed_hdr->ethernet.dst = htonll(parsed_hdr->ethernet.dst << 16);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.src = htonll(parsed_hdr->ethernet.src << 16);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.etherType = bpf_htons(parsed_hdr->ethernet.etherType);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.etherType))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.etherType))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

        }
;        if (parsed_hdr->ip4.ebpf_valid) {
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160)) {
                return TC_ACT_SHOT;
            }
            
            ebpf_byte = ((char*)(&parsed_hdr->ip4.version))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 4, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;

            ebpf_byte = ((char*)(&parsed_hdr->ip4.ihl))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 0, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;

            ebpf_byte = ((char*)(&parsed_hdr->ip4.dscp))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 6, 2, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 6;

            ebpf_byte = ((char*)(&parsed_hdr->ip4.ecn))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 2, 0, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 2;

            parsed_hdr->ip4.len = bpf_htons(parsed_hdr->ip4.len);
            ebpf_byte = ((char*)(&parsed_hdr->ip4.len))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.len))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ip4.id = bpf_htons(parsed_hdr->ip4.id);
            ebpf_byte = ((char*)(&parsed_hdr->ip4.id))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.id))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            ebpf_byte = ((char*)(&parsed_hdr->ip4.flags))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 3, 5, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 3;

            parsed_hdr->ip4.fragOffset = bpf_htons(parsed_hdr->ip4.fragOffset << 3);
            ebpf_byte = ((char*)(&parsed_hdr->ip4.fragOffset))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 5, 0, (ebpf_byte >> 3));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0 + 1, 3, 5, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.fragOffset))[1];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 1, 5, 0, (ebpf_byte >> 3));
            ebpf_packetOffsetInBits += 13;

            ebpf_byte = ((char*)(&parsed_hdr->ip4.ttl))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            ebpf_byte = ((char*)(&parsed_hdr->ip4.protocol))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ip4.checksum = bpf_htons(parsed_hdr->ip4.checksum);
            ebpf_byte = ((char*)(&parsed_hdr->ip4.checksum))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.checksum))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ip4.srcAddr = htonl(parsed_hdr->ip4.srcAddr);
            ebpf_byte = ((char*)(&parsed_hdr->ip4.srcAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.srcAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.srcAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.srcAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ip4.dstAddr = htonl(parsed_hdr->ip4.dstAddr);
            ebpf_byte = ((char*)(&parsed_hdr->ip4.dstAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.dstAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.dstAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip4.dstAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;

        }
;        if (parsed_hdr->ip6.ebpf_valid) {
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 320)) {
                return TC_ACT_SHOT;
            }
            
            ebpf_byte = ((char*)(&parsed_hdr->ip6.version))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 4, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;

            ebpf_byte = ((char*)(&parsed_hdr->ip6.trafficClass))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 0, (ebpf_byte >> 4));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0 + 1, 4, 4, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ip6.flowLabel = htonl(parsed_hdr->ip6.flowLabel << 12);
            ebpf_byte = ((char*)(&parsed_hdr->ip6.flowLabel))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 0, (ebpf_byte >> 4));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0 + 1, 4, 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.flowLabel))[1];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 1, 4, 0, (ebpf_byte >> 4));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 1 + 1, 4, 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.flowLabel))[2];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 2, 4, 0, (ebpf_byte >> 4));
            ebpf_packetOffsetInBits += 20;

            parsed_hdr->ip6.len = bpf_htons(parsed_hdr->ip6.len);
            ebpf_byte = ((char*)(&parsed_hdr->ip6.len))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.len))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            ebpf_byte = ((char*)(&parsed_hdr->ip6.nextHdr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            ebpf_byte = ((char*)(&parsed_hdr->ip6.hopLimit))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[6];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 6, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[7];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 7, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[8];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 8, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[9];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 9, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[10];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 10, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[11];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 11, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[12];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 12, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[13];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 13, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[14];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 14, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.srcAddr))[15];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 15, (ebpf_byte));
            ebpf_packetOffsetInBits += 128;

            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[6];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 6, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[7];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 7, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[8];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 8, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[9];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 9, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[10];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 10, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[11];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 11, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[12];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 12, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[13];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 13, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[14];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 14, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ip6.dstAddr))[15];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 15, (ebpf_byte));
            ebpf_packetOffsetInBits += 128;

        }
;
    }
    return -1;
}
SEC("classifier/tc-ingress")
int tc_ingress_func(struct __sk_buff *skb) {
    struct psa_global_metadata *compiler_meta__ = (struct psa_global_metadata *) skb->cb;
    if (compiler_meta__->pass_to_kernel == true) return TC_ACT_OK;
    if (compiler_meta__->packet_path == NORMAL) {
        compiler_meta__->mark = 153;
        struct internal_metadata *md = (struct internal_metadata *)(unsigned long)skb->data_meta;
        if ((void *) ((struct internal_metadata *) md + 1) <= (void *)(long)skb->data) {
            __u16 *ether_type = (__u16 *) ((void *) (long)skb->data + 12);
            if ((void *) ((__u16 *) ether_type + 1) > (void *) (long) skb->data_end) {
                return TC_ACT_SHOT;
            }
            *ether_type = md->pkt_ether_type;
        }
    }
    struct psa_ingress_output_metadata_t ostd = {
            .drop = true,
    };

    struct empty_t resubmit_meta;
    struct hdr_md *hdrMd;
    struct headers *parsed_hdr;
    int ret = -1;
    #pragma clang loop unroll(disable)
    for (int i = 0; i < 4; i++) {
        ostd.resubmit = 0;
        ret = process(skb, (struct headers *) parsed_hdr, &ostd, compiler_meta__, &resubmit_meta);
        if (ostd.drop == 1 || ostd.resubmit == 0) {
            break;
        }
    }
    if (ret != -1) {
        return ret;
    }
    if (ostd.multicast_group != 0) {
        do_packet_clones(skb, &multicast_grp_tbl, ostd.multicast_group, NORMAL_MULTICAST, 2);
        return TC_ACT_SHOT;
    }
    skb->priority = ostd.class_of_service;
    if (!ostd.drop && ostd.egress_port == 0) {
        compiler_meta__->pass_to_kernel = true;
        return bpf_redirect(skb->ifindex, BPF_F_INGRESS);
    }
    return bpf_redirect(ostd.egress_port, 0);
}

SEC("classifier/tc-egress")
int tc_egress_func(SK_BUFF *skb) {
    struct psa_global_metadata *compiler_meta__ = (struct psa_global_metadata *) skb->cb;
    if (compiler_meta__->mark != 153) {
        return TC_ACT_OK;
    }
    unsigned ebpf_packetOffsetInBits = 0;
    unsigned ebpf_packetOffsetInBits_save = 0;
    ParserError_t ebpf_errorCode = NoError;
    void* pkt = ((void*)(long)skb->data);
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u32 ebpf_zero = 0;
    u32 ebpf_one = 1;
    unsigned char ebpf_byte;
    u32 pkt_len = skb->len;
    u32 ebpf_input_port = skb->ifindex;
    if (ebpf_input_port == PSA_PORT_RECIRCULATE) {
        ebpf_input_port = P4C_PSA_PORT_RECIRCULATE;
    }
    struct metadata_t *meta;

    struct hdr_md *hdrMd;
    struct headers *parsed_hdr;
    hdrMd = BPF_MAP_LOOKUP_ELEM(hdr_md_cpumap, &ebpf_one);
    if (!hdrMd)
        return TC_ACT_SHOT;
    __builtin_memset(hdrMd, 0, sizeof(struct hdr_md));

    parsed_hdr = &(hdrMd->cpumap_hdr);
    meta = &(hdrMd->cpumap_usermeta);
    struct psa_egress_output_metadata_t ostd = {
       .clone = false,
            .drop = false,
        };

    struct psa_egress_input_metadata_t istd = {
            .class_of_service = skb->priority,
            .egress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
            .instance = compiler_meta__->instance,
            .parser_error = ebpf_errorCode,
        };
    {
        struct psa_egress_parser_input_metadata_t istd = {
            .egress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
        };
        goto start;
        start: {
             goto accept;
        }

        reject: {
            if (ebpf_errorCode == 0) {
                return TC_ACT_SHOT;
            }
            goto accept;
        }

    }
    accept:
    istd.parser_error = ebpf_errorCode;

    {

        u8 hit_0;
        {
/* forward_action() */
{
                ostd.drop = false;
                                ostd.clone = false;
            };
        }
    }
    {
{
        }

        int outHeaderLength = 0;

        int outHeaderOffset = BYTES(outHeaderLength) - BYTES(ebpf_packetOffsetInBits);
        if (outHeaderOffset != 0) {
            int returnCode = 0;
            returnCode = bpf_skb_adjust_room(skb, outHeaderOffset, 1, 0);
            if (returnCode) {
                return TC_ACT_SHOT;
            }
        }
        pkt = ((void*)(long)skb->data);
        ebpf_packetEnd = ((void*)(long)skb->data_end);
        ebpf_packetOffsetInBits = 0;

    }
    if (ostd.clone) {
        do_packet_clones(skb, &clone_session_tbl, ostd.clone_session_id, CLONE_E2E, 3);
    }

    if (ostd.drop) {
        return TC_ACT_SHOT;;
    }

    if (istd.egress_port == P4C_PSA_PORT_RECIRCULATE) {
        compiler_meta__->packet_path = RECIRCULATE;
        return bpf_redirect(PSA_PORT_RECIRCULATE, BPF_F_INGRESS);
    }

    
    return TC_ACT_OK;
}
char _license[] SEC("license") = "GPL";
